### ISSUE TITLE
crash 1.20.1 forge

### ISSUE THREAD

**Issue by Thunderrock424242** [quek04/The-Undergarden#181]
[latest.log](https://github.com/quek04/The-Undergarden/files/14307527/latest.log)

**Comment by GizmoTheMoonPig** [comment]
fixed in a newer build, curseforge is taking its sweet time approving builds so it may be a while

**Comment by uhloin** [comment]
Not fixed even in most recent 
Normal loading with version The_Undergarden-1.20.1-0.8.9.jar 
Crash on attempt to load world with The_Undergarden-1.20.1-0.8.12.jar 
The dump is in the attachment

[crash-2024-02-16_19.43.34-client.txt](https://github.com/quek04/The-Undergarden/files/14313085/crash-2024-02-16_19.43.34-client.txt)

**Comment by uhloin** [comment]
Thank you for fast fix in .13 version!
